variables: variables.yml

templates:
  tv-template:
    include: series.yml

    transmission:
      enabled: yes
      host: localhost
      port: 9091
      username: {? transmission.username ?}
      password: {? transmission.password ?}

tasks:

  showrss.info:
    priority: 1
    rss: http://showrss.info/user/{? showrss.id ?}.rss?magnets=true&namespaces=false&name=null&quality=anyhd&re=null
    template: tv-template

  rarbg:
    priority: 2
    rss: https://rarbg.to/rss.php
    template: tv-template

  zooqle:
    priority: 3
    rss: https://zooqle.com/search?q=%2A&fmt=rss
    template: tv-template

  norbits.net:
    priority: 4
    rss: http://norbits.net/rss.php?feed=dl&passkey={? norbits.passkey ?}&format=bb
    template: tv-template
    private_torrents: yes


