templates:
  tv:

    series:
      settings:
        tv:
          propers: 7 days
          set:
            path: /Volumes/TV/{{series_name}}
      tv:
        - Abandoned
        - Action Bronson And Friends Watch Ancient Aliens
        - Adventure Time
        - Arrested Development
        - Balls Deep
        - Better Call Saul
        - Black Market
        - Black Market Dispatches
        - Black Mirror
        - Bobs Burgers
        - Bong Apetit
        - Bravest Warriors
        - Curb Your Enthusiasm
        - Cyberwar
        - Flaked
        - Folkeopplysningen
        - Fuck Thats Delicious
        - Game of Thrones
        - Gaycation
        - Genius
        - Hamiltons Pharmacopeia
        - Huangs World
        - Louis Theroux
        - Louis Theroux Dark States
        - Mr. Robot
        - Narcos
        - Noisey
        - Planet Earth
        - Rick and Morty
        - Saturday Night Live
        - Sherlock
        - Silicon Valley
        - Stranger Things
        - Teenage Boss
        - The Last Man on Earth
        - Trailer Park Boys
        - Trygdekontoret
        - Vice
        - VICE Does America
        - Vice Essentials
        - VICE Lab
        - Vice On HBO
        - Viceland
        - Weediquette
        - Westworld
#        - 20 Aar Med Espen Eckbo
#        - Breaking Bad
#        - Chelsea
#        - Downton Abbey
#        - Indian Summers
#        - Modern Family
#        - MythBusters
#        - Planet Earth 2
#        - Planet Earth II
#        - Planet Earth Two
#        - Prison Break
#        - South Park
#        - The Knick
#        - The Last Panthers
#        - The Office
#        - The Simpsons

    transmission:
      enabled: yes
      host: localhost
      port: 9091
      username: admin
      password: admin

tasks:

  rarbg:
    priority: 1
    rss: https://rarbg.to/rss.php
    template: tv

  extratorrents:
    priority: 5
    rss: https://extratorrents.unblockall.xyz/rss.xml?type=popular&cid=8
    template: tv

  limetorrents:
    priority: 4
    rss: https://www.limetorrents.cc/rss/20/
    template: tv

  zooqle:
    priority: 6
    rss: https://zooqle.com/search?q=%2A&fmt=rss
    template: tv

  norbits.net:
    priority: 7
    rss: http://norbits.net/rss.php?feed=dl&passkey=74bc1121a91304aafb129c9dde9d8e95&format=bb
    template: tv
    private_torrents: yes

  ezrss.it:
    priority: 8
    rss: https://eztv.ag/ezrss.xml
    template: tv
    verify_ssl_certificates: no

  showrss.info:
    priority: 9
    rss: http://showrss.info/user/134388.rss?magnets=true&namespaces=true&name=null&quality=null&re=null
    template: tv
