variables: variables.yml

templates:
  tv-template:
    include: series.yml

    transmission:
      enabled: yes
      host: localhost
      port: 9091
      username: '{? transmission.username ?}'
      password: '{? transmission.password ?}'

tasks:
  movies:
    inputs: 
      - rss: http://norbits.net/rss.php?feed=dl&passkey={? norbits.passkey ?}&format=bb
      - rss: https://rarbg.to/rssdd.php?category=44;45
    proper_movies: yes
    seen_movies: loose
    list_match:
      from:
        - movie_list: movies
    quality: 720p+ webrip+
    imdb_lookup: yes
    transmission:
      enabled: yes
      host: localhost
      port: 9091
      username: '{? transmission.username ?}'
      password: '{? transmission.password ?}'
      path: /Volumes/Movies
      
  iptorrents:
    priority: 1
    rss: https://iptorrents.com/t.rss?u={? iptorrents.id ?};tp={? iptorrents.tp ?};48;7;20;38;100;89;101;68;62;6;90;77;96;87;54;22;99;4;5;78;66;79;65;55;23;25;26;82;24;83;download
    template: tv-template
    private_torrents: yes

  norbits.net:
    priority: 2
    rss: http://norbits.net/rss.php?feed=dl&passkey={? norbits.passkey ?}&format=bb
    template: tv-template
    private_torrents: yes
